name: Destroy AWS Infra

on:
  workflow_dispatch:
  # pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Change WORKDIR
        run: cd dev/
      
      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     # terraform_version: 0.13.0
      #     cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan 
        run: terraform plan -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false