name: Create AWS Infra

on:
  push:
    branches: [master]
  # pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:      ${{secrets.AWS_ACCESS_KEY_ID}} 
      AWS_SECRET_ACCESS_KEY:  ${{secrets.AWS_SECRET_ACCESS_KEY}} 
      GITHUB_TOKEN:           ${{secrets.GITHUB_TOKEN}}

    steps:
      - name: Create Tag version
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create release version
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true

      - name: configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Checkout Codebase
        uses: actions/checkout@v2
      
      - name: Terraform Initialize
        run: terraform init

      - name: Terraform plan 
        uses: dflook/terraform-plan@v1

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
